server:
  port: 8888
spring:
  application:
    name: cloud-config-server
    
  cloud:
    config:
      server:
        git:
          uri: 
          ignore-local-ssh-settings: true
          strict-host-key-checking: false
          search-paths:
          - configuration/{application}/
          - configuration/
          private-key: 
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8700/eureka/
